### ISSUE TITLE
generating clientToken

### ISSUE THREAD

**Issue by cheffplayer** [link3337/ExaltAccountManager#2]
i play this game on linux, so i decided to make my own account manager as a bash script. i looked through your project as a reference, and i came across your [clientToken generator](https://github.com/link3337/ExaltAccountManager/blob/c5e32ecff92bcc22033e8e99d0cbf3b88b066761/src/ExaltAccountManager.Core/Util/Helper.cs#L52) how exactly did you figure out how to generate them? using random inputs doesnt work for me, since the `AccessToken` seems to be affected by what `clientToken` you use. I had to use a network monitor to get the correct `clientToken` for me. 

is there another way to generate these tokens? i cannot use the WMI api on linux, so it would be cool if there was another way to do it. i want to release this script for other linux users, but getting the `clientToken` from deca is very tedious. thank you for any answers.

**Comment by MaikEight** [comment]
Not sure if this helps, this is what the deca-launcher uses: https://docs.unity3d.com/ScriptReference/SystemInfo-deviceUniqueIdentifier.html

**Comment by link3337** [comment]
Just saw this issue now after Maik replied. Not sure if the Unity Docs have Linux related stuff but ty @MaikEight 
@cheffplayer tbh I don't really think the clientToken matters, you can try calling the "/account/verify" endpoint with the clientToken being "0" and it should still give you an accessToken. If you somehow get the "Token for different machine" error when using that accessToken you need to find the exalt launcher's token anyways.

**Comment by MaikEight** [comment]
@link3337 I got a question, If I use random data for the clientToken, I always get the "Token for different machine" (want to add a feature to use a "fake" HWID for the token-generation. Do you know a way to fix that?

**Comment by link3337** [comment]
@MaikEight unfortunately I don't know how to fix that.
I added some kind of way to bypass it but the people need to know how to use Fiddler and check the request headers and see what the actual launcher uses as clientToken (not really trivial at all).

**Comment by MaikEight** [comment]
@link3337 Yeah using fiddler seems to be asking too much from most ppl. 
I thought about creating a small unity project that just returns the clientToken using the real unity implementation for that.

**Comment by cheffplayer** [comment]
> Just saw this issue now after Maik replied. Not sure if the Unity Docs have Linux related stuff but ty @MaikEight
> @cheffplayer tbh I don't really think the clientToken matters, you can try calling the "/account/verify" endpoint with the clientToken being "0" and it should still give you an accessToken. If you somehow get the "Token for different machine" error when using that accessToken you need to find the exalt launcher's token anyways.

yeah i had to use fiddler since using any other access token was giving me that error. the unity documentation for the HWID says that it can generate one for unsupported platforms, so this could be useful as long as you can export it for all operating systems.
> @link3337 Yeah using fiddler seems to be asking too much from most ppl.
> I thought about creating a small unity project that just returns the clientToken using the real unity implementation for that.

i dont use unity, so im not sure how good it is with that. 
either way, i am happy that i was able to get as far as i did. i just dont want to release my own access token since i dont want deca to ban it or something, so ill have to wait for alternative ways to generate them.

**Comment by MaikEight** [comment]
> > @link3337 Yeah using fiddler seems to be asking too much from most ppl.
> > I thought about creating a small unity project that just returns the clientToken using the real unity implementation for that.
> 
> i dont use unity, so im not sure how good it is with that.
> either way, i am happy that i was able to get as far as i did. i just dont want to release my own access token since i dont want deca to ban it or something, so ill have to wait for alternative ways to generate them.

The Unity implementation is exactly what deca is using in theire project. It is fairly simple to use aswell 
`Debug.Log(SystemInfo.deviceUniqueIdentifier); //Returns the clientToken to the console.`
The only downside is: You need to build it as a unity project, wich is going to have about 50MB or so.
My thought is that you just start it silent (-batchmode) and it simply generates a savefile with your clientToken in it - wich your tool can just read and use.

Anyways, that is what I want to test out.
If you want the Unity tool, feel free to use it - once I upload it to my repo!

**Comment by cheffplayer** [comment]
> > > @link3337 Yeah using fiddler seems to be asking too much from most ppl.
> > > I thought about creating a small unity project that just returns the clientToken using the real unity implementation for that.
> > 
> > 
> > i dont use unity, so im not sure how good it is with that.
> > either way, i am happy that i was able to get as far as i did. i just dont want to release my own access token since i dont want deca to ban it or something, so ill have to wait for alternative ways to generate them.
> 
> The Unity implementation is exactly what deca is using in theire project. It is fairly simple to use aswell
> `Debug.Log(SystemInfo.deviceUniqueIdentifier); //Returns the clientToken to the console.`
> The only downside is: You need to build it as a unity project, wich is going to have about 50MB or so.
> My thought is that you just start it silent (-batchmode) and it simply generates a savefile with your clientToken in it - wich your tool can just read and use.
> 
> Anyways, that is what I want to test out.
> If you want the Unity tool, feel free to use it - once I upload it to my repo!

thanks a lot, ill keep a look out for it. as long as it's a native linux binary, then it probably wont have any issues

**Comment by link3337** [comment]
Yea sadly you cannot just integrate the UnityEngine Library, it has to be standalone... @MaikEight

**Comment by MaikEight** [comment]
> Yea sadly you cannot just integrate the UnityEngine Library, it has to be standalone... @MaikEight

Yes, that's why I just build a Unity "game" with the sole purpose of getting the clientToken and saving it on the PC.
But that "game" is hoing to have about 50MB as it needs the whole unity engine aswell.

**Comment by MaikEight** [comment]
I made this "tool" and will publish it this week, going to make sure to let you know when this will happen.
It's a simple Unity project that saves the HWID in a file and closes itself (can be started with the argument -batchmode to start it silently, takes about 1-2 seconds to finish).
Only downside is that it's about 55MB in size as it has to include the unity engine obv.

**Comment by MaikEight** [comment]
As promised, here is the link to my tool, use it if you want: https://github.com/MaikEight/EAM-GetClientHWID/releases/tag/v1.0.0

**Comment by cheffplayer** [comment]
> As promised, here is the link to my tool, use it if you want: https://github.com/MaikEight/EAM-GetClientHWID/releases/tag/v1.0.0

thanks for the upload, it does export the correct clientToken into a text file when i run it with wine. would you be able to package a linux binary in the release as well? i have zero experience with unity, so im not sure if its as easy as clicking a single button when exporting.

**Comment by MaikEight** [comment]
> > As promised, here is the link to my tool, use it if you want: https://github.com/MaikEight/EAM-GetClientHWID/releases/tag/v1.0.0
> 
> thanks for the upload, it does export the correct clientToken into a text file when i run it with wine. would you be able to package a linux binary in the release as well? i have zero experience with unity, so im not sure if its as easy as clicking a single button when exporting.

It certainly won’t be hard to do a Linux release, but I currently don’t have a Linux based system at hand to test it. I can offer you to build it and you test it + report back on the results. 

Can’t do it now though, since I am not at home.

**Comment by MaikEight** [comment]
@link3337 Here you go: https://github.com/MaikEight/EAM-GetClientHWID/releases/tag/v1.0.0
I just build it and did not attempt to run it (got no linux device here at the moment), I hope it works!

You can start this tool with the arguments: "EAM GetClientHWID.exe -batchmode {Path\To\Folder}" to create the EAM.HWID in the desired folder. If no path is specified it will create the EAM.HWID file in the same folder as the executable.

That arguments are for the windows version, linux should have similar syntax (the {path/folder/} part is by design, so you need to use the curly brackets). 
Would be nice if you could report back if it's working or not.

**Comment by cheffplayer** [comment]
thanks for the linux binary, it runs just fine and gets me a HWID. the problem with it is that i get the "token for different machine" error, so does that mean that each account is hardlinked to a single HWID?

**Comment by MaikEight** [comment]
Each Token is bound to a single HWID, as soon as you start the game, it checks your HWID and matches it with the token you gave the game. The "token for different machine"-error means the tool gives you the wrong HWID. I am not aware how they get it on Linux systems, they could use a different methode than on windows (unlikely but possible).

If you look into the[ code behind my small tool ](https://github.com/MaikEight/EAM-GetClientHWID/blob/master/Assets/GetHWID.cs) you will see that I just save the value: `SystemInfo.deviceUniqueIdentifier` into a file. So I am not sure what could be the cause here.

**Comment by cheffplayer** [comment]
> Each Token is bound to a single HWID, as soon as you start the game, it checks your HWID and matches it with the token you gave the game. The "token for different machine"-error means the tool gives you the wrong HWID. I am not aware how they get it on Linux systems, they could use a different methode than on windows (unlikely but possible).
> 
> If you look into the[ code behind my small tool ](https://github.com/MaikEight/EAM-GetClientHWID/blob/master/Assets/GetHWID.cs) you will see that I just save the value: `SystemInfo.deviceUniqueIdentifier` into a file. So I am not sure what could be the cause here.

i think the code for the game specifically looks out for the HWIDs that can only get generated using the WMI api on windows. since linux does not use this api, unity gives out a different HWID to linux users. 
oh well, at least we know that running your tool with Wine can still generate the correct HWID. thanks for all the work you've done, i will just have to work with what i got

**Comment by link3337** [comment]
@MaikEight your tool works great, had someone test it and I tested it aswell, good job! (both windows)

**Comment by MaikEight** [comment]
> @MaikEight your tool works great, had someone test it and I tested it aswell, good job! (both windows)

Thanks for the praise!
I already did include it into my EAM, alongside new modules like a ping checker, game updater, UI improvements and more.
Everyone that couldn't use the EAM due to a "token for different machine" can do it now with the HWID Tool - verified by two ppl that contacted me with that error a while ago.

I am not sure about the linux-release, but I only investigate it if it would be necessary to do so.
